name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0-23/1 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email canmicn@gmail.com
          git config --local user.name Canmi
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Update"
          git push
